import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS });

  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return json({ error: "Unauthorized" }, 401);

  // User-scoped client (respects RLS)
  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
    { global: { headers: { Authorization: authHeader } } },
  );

  // Admin client — used to bypass RLS for invite operations
  const supabaseAdmin = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) return json({ error: "Unauthorized" }, 401);

  const body = await req.json();
  const { invitedEmail } = body;
  if (!invitedEmail || typeof invitedEmail !== "string") {
    return json({ error: "invitedEmail is required" }, 400);
  }
  const email = invitedEmail.trim().toLowerCase();

  if (user.email?.toLowerCase() === email) {
    return json({ error: "You cannot invite yourself" }, 400);
  }

  // Reject if an active partner link already exists
  const { data: existingAccess } = await supabaseAdmin
    .from("partner_access")
    .select("id")
    .eq("master_user_id", user.id)
    .maybeSingle();
  if (existingAccess) {
    return json(
      { error: "You already have an active partner link. Remove it first." },
      409,
    );
  }

  // Remove any stale pending invite for this master before creating a new one
  await supabaseAdmin
    .from("partner_invites")
    .delete()
    .eq("master_user_id", user.id);

  // Insert new invite (token is auto-generated by DB default)
  const { data: invite, error: inviteError } = await supabaseAdmin
    .from("partner_invites")
    .insert({ master_user_id: user.id, invited_email: email })
    .select()
    .single();
  if (inviteError) {
    console.error("invite insert error:", inviteError);
    return json({ error: "Failed to create invite" }, 500);
  }

  // Send email via Resend
  const resendKey = Deno.env.get("RESEND_API_KEY");
  if (!resendKey) return json({ error: "Email service not configured" }, 500);

  const inviteUrl =
    `https://www.brettlabs.dev?tool=spend-analyzer&invite=${invite.token}`;

  const emailRes = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${resendKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "BrettLabs <noreply@brettlabs.dev>",
      to: [email],
      template: {
        id: "spend-analyzer-invitation-1",
        variables: { inviteUrl },
      },
    }),
  });

  if (!emailRes.ok) {
    const errBody = await emailRes.text();
    console.error("Resend error:", errBody);
    return json({ error: "Failed to send invitation email" }, 500);
  }

  return json({ success: true });
});
