export const CARDS = [
  { id: 'fidelity', label: 'Fidelity / ELAN', sub: '' },
  { id: 'barclays', label: 'Barclays', sub: '2 cards' },
  { id: 'verizon', label: 'Verizon Visa', sub: '' },
  { id: 'chase', label: 'Chase', sub: '' },
  { id: 'other', label: 'Other Card', sub: '' },
];

export const CAT_COLORS = {
  'FOOD_AND_DRINK':            '#059669',
  'TRANSPORTATION':            '#0891b2',
  'RENT_AND_UTILITIES':        '#d97706',
  'GENERAL_MERCHANDISE':       '#7c3aed',
  'MEDICAL':                   '#dc2626',
  'ENTERTAINMENT':             '#2563eb',
  'TRAVEL':                    '#db2777',
  'PERSONAL_CARE':             '#ea580c',
  'GENERAL_SERVICES':          '#4f46e5',
  'HOME_IMPROVEMENT':          '#0d9488',
  'BANK_FEES':                 '#65a30d',
  'GOVERNMENT_AND_NON_PROFIT': '#9333ea',
  'OTHER':                     '#6b7280',
};

export const EXCLUDED = ['LOAN_PAYMENTS', 'LOAN_DISBURSEMENTS', 'INCOME', 'TRANSFER_IN', 'TRANSFER_OUT'];

export const SUBCATEGORIES = {
  FOOD_AND_DRINK: [
    'FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR', 'FOOD_AND_DRINK_COFFEE', 'FOOD_AND_DRINK_FAST_FOOD',
    'FOOD_AND_DRINK_GROCERIES', 'FOOD_AND_DRINK_RESTAURANT', 'FOOD_AND_DRINK_VENDING_MACHINES',
    'FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK',
  ],
  TRANSPORTATION: [
    'TRANSPORTATION_BIKES_AND_SCOOTERS', 'TRANSPORTATION_GAS', 'TRANSPORTATION_PARKING',
    'TRANSPORTATION_PUBLIC_TRANSIT', 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES', 'TRANSPORTATION_TOLLS',
    'TRANSPORTATION_OTHER_TRANSPORTATION',
  ],
  RENT_AND_UTILITIES: [
    'RENT_AND_UTILITIES_GAS_AND_ELECTRICITY', 'RENT_AND_UTILITIES_INTERNET_AND_CABLE',
    'RENT_AND_UTILITIES_RENT', 'RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT',
    'RENT_AND_UTILITIES_TELEPHONE', 'RENT_AND_UTILITIES_WATER', 'RENT_AND_UTILITIES_OTHER_UTILITIES',
  ],
  GENERAL_MERCHANDISE: [
    'GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS', 'GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES',
    'GENERAL_MERCHANDISE_CONVENIENCE_STORES', 'GENERAL_MERCHANDISE_DEPARTMENT_STORES',
    'GENERAL_MERCHANDISE_DISCOUNT_STORES', 'GENERAL_MERCHANDISE_ELECTRONICS',
    'GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES', 'GENERAL_MERCHANDISE_OFFICE_SUPPLIES',
    'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES', 'GENERAL_MERCHANDISE_PET_SUPPLIES',
    'GENERAL_MERCHANDISE_SPORTING_GOODS', 'GENERAL_MERCHANDISE_SUPERSTORES',
    'GENERAL_MERCHANDISE_TOBACCO_AND_VAPING', 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
  ],
  MEDICAL: [
    'MEDICAL_DENTAL_CARE', 'MEDICAL_EYE_CARE', 'MEDICAL_NURSING_CARE',
    'MEDICAL_PHARMACIES_AND_SUPPLEMENTS', 'MEDICAL_PRIMARY_CARE', 'MEDICAL_VETERINARY_SERVICES',
    'MEDICAL_OTHER_MEDICAL',
  ],
  ENTERTAINMENT: [
    'ENTERTAINMENT_CASINOS_AND_GAMBLING', 'ENTERTAINMENT_CONCERTS_AND_EVENTS', 'ENTERTAINMENT_GOLF',
    'ENTERTAINMENT_GYMS_AND_FITNESS_CENTERS', 'ENTERTAINMENT_MUSEUMS',
    'ENTERTAINMENT_OUTDOORS_AND_RECREATION', 'ENTERTAINMENT_PERFORMING_ARTS',
    'ENTERTAINMENT_SPORTS_EVENTS', 'ENTERTAINMENT_TV_AND_MOVIES', 'ENTERTAINMENT_VIDEO_GAMES',
    'ENTERTAINMENT_OTHER_ENTERTAINMENT',
  ],
  TRAVEL: [
    'TRAVEL_FLIGHTS', 'TRAVEL_HOTELS_AND_MOTELS', 'TRAVEL_RENTAL_CARS',
    'TRAVEL_TRAVEL_AGENCIES', 'TRAVEL_OTHER_TRAVEL',
  ],
  PERSONAL_CARE: [
    'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS', 'PERSONAL_CARE_HAIR_AND_BEAUTY',
    'PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING', 'PERSONAL_CARE_OTHER_PERSONAL_CARE',
  ],
  GENERAL_SERVICES: [
    'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING', 'GENERAL_SERVICES_AUTOMOTIVE',
    'GENERAL_SERVICES_CHILDCARE', 'GENERAL_SERVICES_CONSULTING_AND_LEGAL',
    'GENERAL_SERVICES_EDUCATION', 'GENERAL_SERVICES_INSURANCE',
    'GENERAL_SERVICES_POSTAGE_AND_SHIPPING', 'GENERAL_SERVICES_STORAGE',
    'GENERAL_SERVICES_OTHER_GENERAL_SERVICES',
  ],
  HOME_IMPROVEMENT: [
    'HOME_IMPROVEMENT_FURNITURE', 'HOME_IMPROVEMENT_HARDWARE', 'HOME_IMPROVEMENT_LANDSCAPING',
    'HOME_IMPROVEMENT_POOLS_AND_HOT_TUBS', 'HOME_IMPROVEMENT_SECURITY',
    'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT',
  ],
  BANK_FEES: [
    'BANK_FEES_ATM_FEES', 'BANK_FEES_FOREIGN_TRANSACTION_FEES', 'BANK_FEES_INSUFFICIENT_FUNDS',
    'BANK_FEES_INTEREST_CHARGE', 'BANK_FEES_OVERDRAFT_FEES', 'BANK_FEES_OTHER_BANK_FEES',
  ],
  GOVERNMENT_AND_NON_PROFIT: [
    'GOVERNMENT_AND_NON_PROFIT_DONATIONS',
    'GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES',
    'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT',
    'GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT',
  ],
  INCOME: [
    'INCOME_DIVIDENDS', 'INCOME_INTEREST_EARNED', 'INCOME_RETIREMENT_PENSION',
    'INCOME_TAX_REFUND', 'INCOME_UNEMPLOYMENT', 'INCOME_WAGES', 'INCOME_OTHER_INCOME',
  ],
  LOAN_PAYMENTS: [
    'LOAN_PAYMENTS_CAR_PAYMENT', 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
    'LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT', 'LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT',
    'LOAN_PAYMENTS_OTHER_PAYMENT',
  ],
  LOAN_DISBURSEMENTS: [
    'LOAN_DISBURSEMENTS_PERSONAL', 'LOAN_DISBURSEMENTS_AUTO', 'LOAN_DISBURSEMENTS_STUDENT',
  ],
  TRANSFER_IN: [
    'TRANSFER_IN_ACCOUNT_TRANSFER', 'TRANSFER_IN_CASH_ADVANCES_AND_OVERDRAFTS',
    'TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS', 'TRANSFER_IN_SAVINGS',
    'TRANSFER_IN_PAYROLL', 'TRANSFER_IN_OTHER_TRANSFER_IN',
  ],
  TRANSFER_OUT: [
    'TRANSFER_OUT_ACCOUNT_TRANSFER', 'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS',
    'TRANSFER_OUT_SAVINGS', 'TRANSFER_OUT_WITHDRAWAL', 'TRANSFER_OUT_OTHER_TRANSFER_OUT',
  ],
  OTHER: ['OTHER_OTHER'],
};
